'open grid.ctl'
'set parea 0 11 0 8.5'
'set ylab off'
'set xlab off'
'set grads off'
'set grid off'
'set mpdset hires'
'set map 1'
'set mproj scaled'
'set clevs -999'
'd var'
'printim climdivmap1.png x800 y600'
#'quit'
